### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by rentalhost** [mskelton/vscode-npm-outdated#10]
Hello! I have installed it on vscode 1.74.0, but it seems no works as expected. It can't detect outdated packages. I don't know how can I help you better, but if there are something that I could do, please tell me.

![image](https://user-images.githubusercontent.com/421851/206601755-10f907ef-41e3-44d8-a356-2b1d37ed27e8.png)

The package `typescript`, for instance, is on `^4.9.4`, but it is not displayed on `package.json`.

![image](https://user-images.githubusercontent.com/421851/206602011-8e9b2da7-98d8-4b03-ac99-ea302d6850b6.png)
![image](https://user-images.githubusercontent.com/421851/206602035-b6b8ca7f-2d01-49e9-a62f-2366c1d18354.png)

It's supposed to works, right?

**Comment by mskelton** [comment]
I haven't used or maintained this extension in several years, so mileage may vary.  Feel free to fork the project if you are interested in digging into the issue.

**Comment by rentalhost** [comment]
@mskelton I'm digging through the code here, and I realized that maybe the problem is that I'm in a Windows environment, and this part of the code fails:

https://github.com/mskelton/vscode-npm-outdated/blob/fc397724ceb1b42b66f010c96f5bf9bcb26b4ec0/src/diagnostics/subscribeToDocument.ts#L8-L12

While on Unix the path actually ends with `/package.json`, on Windows it is `\package.json`.

As I'm wanting to understand how extensions work in vscode (I came from PhpStorm), I'm thinking of rewriting your extension, just for learning purposes. If I conclude, would you think it's a good idea to update yours as 2.0, or do you prefer that I keep a separate package in vscode Extensions? (if I come to complete it)

In practice, I'm using 99% of your code, just using a newer "wrapper" as per the vscode documentation.

**Comment by mskelton** [comment]
> As I'm wanting to understand how extensions work in vscode (I came from PhpStorm), I'm thinking of rewriting your extension, just for learning purposes. If I conclude, would you think it's a good idea to update yours as 2.0, or do you prefer that I keep a separate package in vscode Extensions? (if I come to complete it)

If you'd like to rewrite and submit pull requests I'll happily review and merge them.

**Comment by rentalhost** [comment]
I made a PR #11.

Update avaliable example:
![image](https://user-images.githubusercontent.com/421851/206886911-e1148f01-e57f-4634-b62c-0a2ac5f0e3f1.png)

---

Invalid version example:
![image](https://user-images.githubusercontent.com/421851/206886921-c1c0cc56-bae1-493b-875e-addf09289f8c.png)

---

"Future" version example:
![image](https://user-images.githubusercontent.com/421851/206886924-114eba22-86dd-434f-883b-ccf5cce5bffb.png)

---

Right-click on a single version:
![image](https://user-images.githubusercontent.com/421851/206886966-7f6e91e5-c405-47ca-b3a2-46916ababa89.png)

---

Two versions selected:
![image](https://user-images.githubusercontent.com/421851/206886980-52a43fdc-0652-480f-8366-86870cd0f8cb.png)

---

All versions selected:
![image](https://user-images.githubusercontent.com/421851/206886986-bf35d7b7-eb1e-4e50-a17e-50492d55cc57.png)

---

Notification:
![image](https://user-images.githubusercontent.com/421851/206887013-2108905a-faea-4456-9a50-058ae46ba4f7.png)

---

Run output:
![image](https://user-images.githubusercontent.com/421851/206887072-7e7afbda-c1d9-4cbe-b88b-f67a05555baf.png)

**Comment by mskelton** [comment]
https://github.com/mskelton/vscode-npm-outdated/releases/tag/v2.0.0
