### ISSUE TITLE
Package update information text seems borked upon todays VScode update

### ISSUE THREAD

**Issue by sammcj** [mskelton/vscode-npm-outdated#23]
Getting some funky text distortion on npm outdated's update information after updating VSCode today:

![image](https://github.com/mskelton/vscode-npm-outdated/assets/862951/d6bd8d41-158a-467a-bf3b-90ed571b8e42)

- All other plugins seem to be operating normally.
- No other plugins provide update text for npm packages that could be clashing.
- macOS 13.4.1
- VSCode 1.80.0

Is this a known issue?

**Comment by rentalhost** [comment]
Is this happening consistently? The _vscode_ has some difficulty handling colored text like this, and I had **[reported](https://github.com/microsoft/vscode/issues/169051)** it to them, but they simply ignored it and said it's intended behavior.

As an alternative, there is an option in the extension to disable the color system (search for `npm-outdated.decorations` in the settings). However, the recent changes in PR #22 may potentially solve this issue.

Since it hasn't been reviewed and approved yet, I'll provide an option here to download it and manually install it in vscode.

https://drive.google.com/file/d/1AxQFX09m_eD86_dWuF0mHN4EZ3g3afAc/view?usp=sharing

**Comment by sammcj** [comment]
Yeah it is consistent and reproducible.

I wouldn't be surprised if it clashed with one of the many other VSCode extensions that format text - but haven't been able to pin down which one if so (and haven't added any new extensions).

Thanks for alerting me to `npm-outdated.decorations` - setting that to disabled resolves the issue for me - not ideal but at least I can read it now!

**Comment by rentalhost** [comment]
@sammcj Do you think you can create a reduced test package? I believe package.json, package-lock.json (or similar) might be reproducible.

**Comment by sammcj** [comment]
Sure thing, here's a zip with package.json, package-lock.json where the text gets overlapped.

[Archive.zip](https://github.com/mskelton/vscode-npm-outdated/files/12065542/Archive.zip)

![image](https://github.com/mskelton/vscode-npm-outdated/assets/862951/69a67bad-0623-4a5d-bdfc-b177e286c51f)

Enabled VScode packages:

- NPM Outdated
- NPM Intellisense
- Error Lens
- Better Comments
- ESLint

And confirming that setting `"npm-outdated.decorations": "disabled"` fixes the issue.

**Comment by rentalhost** [comment]
Unfortunately, I couldn't reproduce it in either the current version or the PR #22 version. Both worked perfectly. It seems that there is a conflict with the _Error Lens_ extension.

![image](https://github.com/mskelton/vscode-npm-outdated/assets/421851/46246fdb-30bf-4f3a-a688-1c6e1e4c14ed)

I believe this bug should be reported directly to the vscode team (I've never had much luck with them, but who knows...). In the meantime, perhaps you can keep the `"npm-outdated.decorations": "disabled"` configuration or temporarily configure _Error Lens_ to _exclude_ `^Newer version of` at settings.

![image](https://github.com/mskelton/vscode-npm-outdated/assets/421851/1e31f4e6-8bb1-46f6-9033-fbcb7f0d30f8)

Additionally, thank you, I didn't know about _Error Lens_, and it seems quite useful.

**Comment by sammcj** [comment]
ahhhh, so npm-outdated is showing those messages as a type of error, and ErrorLens will be those errors up (again)?

If so - I agree, it sounds like it's a core vscode issue where multiple error annotations shouldn't overlap.

ErrorLens is so, _so_ useful - just perhaps not in this specific case 😄.

Sorry for wasting your time on this one! I'll close this off and might log a bug with VScode (at which point I'll link to this).

**Comment by sammcj** [comment]
Oh and a little tip with ErrorLens - I'd highly recommend setting it to show just warn and error level otherwise it can be pretty noisy.

![image](https://github.com/mskelton/vscode-npm-outdated/assets/862951/2efe8027-e066-4820-9602-2e6a9252c88c)
