### ISSUE TITLE
Feature request: Add option to only notify in major/minor/patch version

### ISSUE THREAD

**Issue by dels07** [mskelton/vscode-npm-outdated#4]
Hi,

I don't know how difficult it is, but can you add configuration/setting to extension to only check updated version of package(s) based on their `major/minor/patch` version, so if I choose `minor` if package updated to `patch` version I would not get the lens.

Thanks

**Comment by mskelton** [comment]
I'm definitely open to this idea, though I haven't actually been using this extension recently nor do I have the time at the moment to work on this feature. Is this something you would be interested in working on if I gave some guidance?

**Comment by dels07** [comment]
Sorry for late reply, as I read through the source code, likely it quite easy to add the requested feature, I will try to do that on my free time
