### ISSUE TITLE
Issue Getting Extension to Load After Updating to 1.4.0

### ISSUE THREAD

**Issue by lerickson-ds** [mskelton/vscode-npm-outdated#6]
I couldn't get this extension to work today, even though it was working yesterday and I haven't changed anything. I tried a couple of different things and finally realized it installed a new version this morning. So I solved it by downgrading to 1.3.0 and everything worked great again. I think there might be an issue with 1.4.0.

Here is my VS Code information:
```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0
```

**Comment by mskelton** [comment]
So sorry for the delay, I just pushed a commit that should fix this.  It will be available in version 1.4.1
