### ISSUE TITLE
Feature request: Add option to highlight major/minor/patch version in different colors

### ISSUE THREAD

**Issue by InfamousStarFox** [mskelton/vscode-npm-outdated#8]
Example: major is red, minor is yellow, and patch is blue

**Comment by mskelton** [comment]
I don't use this project anymore, so I won't be adding new features to it.  You're welcome to fork and add this feature and I would accept PRs or you can just maintain your own fork if you'd like.

**Comment by rentalhost** [comment]
@InfamousStarFox It is intended to do something similar to this in the future. I'll update here when I have news.
