### ISSUE TITLE
Feature request: add highlighting for security vulnerabilities

### ISSUE THREAD

**Issue by InfamousStarFox** [mskelton/vscode-npm-outdated#9]
Example: highlight in purple for critical, red for high, and gold for moderate

**Comment by mskelton** [comment]
I don't use this project anymore, so I won't be adding new features to it.  You're welcome to fork and add this feature and I would accept PRs or you can just maintain your own fork if you'd like.

**Comment by rentalhost** [comment]
@InfamousStarFox Do you know how we can check the vulnerability level of packages?

**Comment by rentalhost** [comment]
I researched about it and found that Github itself has a [**GraphQL API**](https://docs.github.com/en/graphql/overview/explorer) that would totally help in this regard.

```graphql
{
  securityVulnerabilities(ecosystem: NPM, first: 100, package: "pg") {
    nodes {
      severity
      vulnerableVersionRange
      advisory {
        permalink
      }
      firstPatchedVersion {
        identifier
      }
    }
  }
}
```

However... Yes, the however... Is that it needs individual _OAuth authentication_. I believe this is unfeasible for the extension at the moment.

What do you say, @mskelton? Do you think it's within the context of this extension, and besides, would it be okay to ask the user to authenticate via OAuth to gain access to this feature?

**Comment by mskelton** [comment]
Hmm, I guess that could work, but I wonder if using `npm audit` could be a way to do this more natively without having to interact with GitHub.

**Comment by rentalhost** [comment]
@mskelton oh, I totally missed this possibility! I will check it today!
